name: Gamemode4Core
version: '${version}'
main: com.kruthers.gamemode4core.Gamemode4Core
api-version: 1.20
author: kruthers
description: The core plugin used to manage the gamemode 4 public server
depend:
  - PandaLib
  - LuckPerms
  - BanManager
  - DiscordSRV
softdepend:
  - PlaceholderAPI
permissions:
  gm4core.default:
    default: true
    description: Base permission used for core command
  gm4core.reload:
    default: false
    description: Used to reload the plugin
  gm4core.mode.watch:
    default: op
    description: Allows you to go into streamer mode and disable notifications
    children:
      - gm4core.mode.mod
  gm4core.mode.mod:
    default: op
    description: Allows you to go into mod mode
  gm4core.tpa:
    default: op
    description: tpa to locations or people
  gm4core.tpa.back:
    default: op
    description: go back to previous locations
    children:
      - gm4core.tpa
  gm4core.freeze:
    default: op
    description: Freeze everyone on the server
  gm4core.freeze.byspass:
    default: op
    description: Bypass getting frozen
  gm4core.freeze.notify:
    default: op
    description: Get notified separately when a freeze is started and of who started it
  gm4core.warp:
    default: op
  gm4core.warp.manage:
    default: op
    children:
      - gm4core.warp
  gm4core.griefwarning:
    default: op
    description: Warns when a attempted grief has occurred
  gm4core.warnings:
    default: true
    description: Lists all your warnings
  gm4core.warnings.others:
    default: op
    description: Lists other players warnings